# The Virtual Jaguar core's C sources (81 files incl. libchdr's unity.c; the per-CPU SIMD blitter is added in CMakeLists.txt), taken from the object list of its
# own desktop build (Makefile.common).  Paths are relative to the core's directory.
set(CORE_SOURCES
    libretro-common/compat/compat_posix_string.c
    libretro-common/compat/compat_snprintf.c
    libretro-common/compat/compat_strcasestr.c
    libretro-common/compat/compat_strl.c
    libretro-common/compat/fopen_utf8.c
    libretro-common/encodings/encoding_utf.c
    libretro-common/file/file_path_io.c
    libretro-common/file/file_path.c
    libretro-common/streams/file_stream_transforms.c
    libretro-common/streams/file_stream.c
    libretro-common/string/stdstring.c
    libretro-common/time/rtime.c
    libretro-common/vfs/vfs_implementation.c
    libretro.c
    src/bios/jagbios_m.c
    src/bios/jagbios.c
    src/bios/jagcdbios.c
    src/bios/jagdevcdbios.c
    src/cd/cdintf.c
    src/cd/cdrom.c
    src/cd/jagcd_bios.c
    src/cd/jagcd_cart.c
    src/cd/jagcd_hle.c
    src/core/biosdb.c
    src/core/bus_arbiter.c
    src/core/cheat.c
    src/core/crash_detect.c
    src/core/crc32.c
    src/core/event.c
    src/core/file.c
    src/core/filedb.c
    src/core/hookfile.c
    src/core/jaggd.c
    src/core/jaguar.c
    src/core/memtrack.c
    src/core/nvmbios.c
    src/core/perf_counters.c
    src/core/perf_iface.c
    src/core/settings.c
    src/core/titledb.c
    src/core/titlehook.c
    src/core/universalhdr.c
    src/core/vjag_memory.c
    src/core/vjtrace.c
    src/debug/gdbsock.c
    src/debug/gdbstub.c
    src/debug/gdbtarget.c
    src/jerry/axistune.c
    src/jerry/dac.c
    src/jerry/dsp.c
    src/jerry/eeprom.c
    src/jerry/inputdev.c
    src/jerry/jerry.c
    src/jerry/jlink_discover.c
    src/jerry/jlink_netpacket.c
    src/jerry/jlink_tcp.c
    src/jerry/jlink.c
    src/jerry/joystick.c
    src/jerry/paddle.c
    src/jerry/quadrature.c
    src/jerry/uart.c
    src/jerry/voicechat.c
    src/jerry/voicemodem.c
    src/jerry/wavetable.c
    src/m68000/cpudefs.c
    src/m68000/cpuemu.c
    src/m68000/cpuextra.c
    src/m68000/cpustbl.c
    src/m68000/m68kinterface.c
    src/m68000/readcpu.c
    src/tom/blit_memo.c
    src/tom/blitter_compare.c
    src/tom/blitter_mmio.c
    src/tom/blitter.c
    src/tom/gpu.c
    src/tom/op.c
    src/tom/shadowfb.c
    src/tom/texdump.c
    src/tom/texreplace.c
    src/tom/tom.c
)
